### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]

### ISSUE THREAD

**Issue by aydybb** [mifi/ezshare#1]
When I download a file with name in Japanese, node throws TypeError as follows.

"
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:488:3)
    at ServerResponse.header (C:\Program Files\Nodejs\node_global\node_modules\ezshare\node_modules\express\lib\response.js:771:10)
    at C:\Program Files\Nodejs\node_global\node_modules\ezshare\index.js:114:9
"

**Comment by mifi** [comment]
Fixed in 1.1.1
