### ISSUE TITLE
AssertionError: Path must be within shared path

### ISSUE THREAD

**Issue by abyssox** [mifi/ezshare#109]
When i start ezshare with a folder parameter i get en error:
```
AssertionError [ERR_ASSERTION]: Path must be within shared path
    at getFileAbsPath (C:\snapshot\ezshare\dist\index.js:58727:36)
    at async C:\snapshot\ezshare\dist\index.js:58832:27
```

App Version: 1.11.2
Command i used: `ezshare.exe c:\01_Tools\ezshare\share\`

**Comment by mifi** [comment]
try again now

**Comment by abyssox** [comment]
:thumbsup: Working now. Thanks
